### ISSUE TITLE
Cannot invoke 'startAdvertising' with an argument list of type

### ISSUE THREAD

**Issue by limfinity** [Intermark/Buoy#6]
Hi,

I tried using your classes, but unfortunately I get an error on line 73 of BUOYBeacon.swift.
"Cannot invoke 'startAdvertising' with an argument list of type '(NSMutableDictionary!)'"

Can you help to resolve this? Thanks. :)

**Comment by bennyguitar** [comment]
Should be working on Master now. Try it out and let me know. Buoy was made before Swift 1.2, so now it should be modernized.
